language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn test

notifications:
  email:
    recipients:
      - wilmion92@gmail.com
      - wilmionreal@gmail.com
    on_success: always
    on_failure: always

deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: ec20ecf5-c38b-4d08-8b0d-a935928533d8
  app: platzi-store-backendd
  on:
    repo: wilmion/platzi-store-backend